version: "3.7"
services:
  kong:
    image: kong:alpine
    depends_on:
      - kong-base
    environment:
      KONG_DATABASE: "cassandra"
      KONG_CASSANDRA_CONTACT_POINTS: "kong-base"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  cassandra-init:
    image: kong:alpine
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-base
    command: kong migrations bootstrap
  kong-base:
    image: cassandra:3